# Generated by Django 5.2.17 on 2026-08-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PLANNED', max_length=20),
        ),
    ]
