# Generated by Django 5.2.17 on 2026-08-24 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_intervention_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
